<?php

$produtos = array(
    0 => array('nome'=>'Placa de Video MSI GeForce RTX 3060 Ti Ventus 2X OCV1, LHR, 8GB, GDDR6, 256-bit, 912-V397-233', 'preco'=>'R$ 3.499,00', 'descricao'=>'Com a GeForce® RTX 3060 Ti e a RTX 3060, você pode jogar os games mais atuais usando o poder da Ampere, a 2ª geração da arquitetura RTX da NVIDIA. Obtenha um desempenho incrível com Ray Tracing Cores e Tensor Cores aprimorados, novos multiprocessadores de streaming e memória G6 de alta velocidade.', 'imagem'=>'produto1.jpg'),
    1 => array('nome'=>'PROCESSADOR INTEL CORE I5-12400, 6-CORE, 12-THREADS, 2.5GHZ (4.4GHZ TURBO), CACHE 18MB, LGA1700, BX8071512400', 'preco'=>'R$ 1.347,90', 'descricao'=>'Projetados para os jogos da próxima geração.Realize mais, com maior desempenho. Dispute com confiança ou mergulhe em novos mundos com uma arquitetura de processadores revolucionária que se concentra no que mais importa — jogos', 'imagem'=>'produto2.jpg'),
    2 => array('nome'=>'MOUSE GAMER PICHAU HIVE S, RGB, 16000DPI, 6 BOTOES. PRETO, PGM-HVSRGB-BLK', 'preco'=>'R$ 169,90', 'descricao'=>'O Hive S conta com um corpo modular, mesclando customização com robustez, mantendo ainda um peso baixo para que você tenha total controle durante sua jogatina. Com seu shape simétrico o Hive S foi projetado para manter a anatomia em qualquer situação.', 'imagem'=>'produto3.jpg'),
    3 => array('nome'=>'HEADSET GAMER PICHAU P852 VEGA, RGB, SOM SURROUND 7.1, DRIVERS 53MM, PRETO, PGH-P852VGA-RGB', 'preco'=>'R$ 399,91', 'descricao'=>'Desenvolvido com materiais de alta qualidade e um design requintado, o P852 é o headset perfeito para qualquer ambiente. Com uma beleza protagonizada pela discrição e simplicidade, pode ser usado em todos os setups, dos gamers aos profissionais.', 'imagem'=>'produto4.jpg'),
    4 => array('nome'=>'CONTROLE GAMER PICHAU GCX100 PC/PS3/ANDROID, PG-CX100-BK', 'preco'=>'R$ 119,90', 'descricao'=>'Controle feito especialmente para que gosta de se sentir nos consoles, o Pichau GCX100 foi adaptado para todos os tipos de gamers dando o maior conforto para jogarem seus jogos.', 'imagem'=>'produto5.jpg'),
    5 => array('nome'=>'WATER COOLER COOLER MASTER MASTERLIQUID 240MM ML240L V2 RGB, MLW-D24M-A18PC-R2', 'preco'=>'R$ 469,90', 'descricao'=>'Water Cooler MAster MasterLiquid, feito especialmente para quem precisa de uma ajuda extra na refrigeração do computador, o MasterLiquid é preparado para enfrentar as maiores batalhas e não te deixar na mão.', 'imagem'=>'produto6.jpg'),
    6 => array('nome'=>'SSD TEAM GROUP GX2 256GB 2.5" SATA 6GB/S, T253X2256G0C101', 'preco'=>'R$ 199,99', 'descricao'=>'Quando seu computador está lento, você sente que ele está prejudicando sua eficiência? Com excelente desempenho e velocidade de leitura e gravação ultrarrápida, a unidade de estado sólido GX2 é 4 vezes mais rápida * do que o disco rígido tradicional. Ele pode não apenas acelerar o tempo de inicialização, tempo de desligamento e tempo de resposta dos aplicativos, mas também é leve e fácil de transportar. É absolutamente o melhor produto para substituir o disco rígido tradicional.', 'imagem'=>'produto7.jpg'),
    7 => array('nome'=>'TECLADO MECANICO LOGITECH G PRO K/DA LEAGUE OF LEGENDS, RGB, US, SWITCH BROWN TACTILE, 920-010074', 'preco'=>'R$ 599,00', 'descricao'=>'Precisando deixar seu setup mais bonito? Com o Logitrch G PRO K/DA LEAGUE OF LEGENDS você consegue. Compacto, durável e ultraportátil. Teclas com switches mecânicos GX Brown Tactile. Iluminação RGB LIGHTSYNC. Perfil integrado para armazenamento de iluminação.', 'imagem'=>'produto8.jpg'),
    8 => array('nome'=>'MONITOR GAMER MULTILASER WARRIOR SHIN KAI, 24 POL. VA CURVO, FHD, 1MS,165HZ, FREESYNC, HDMI/DP, MN103', 'preco'=>'R$ 1.399,90', 'descricao'=>'Multilaser Warrior, perfeito para quem deseja desfrutar de belos 165HZ com 1MS de resposta, ideal para os gamers, além de deixar o setup muito mais bonito.', 'imagem'=>'produto9.jpg'),
    9 => array('nome'=>'WATER COOLER LIAN LI GALAHAD AIO 360, UNI FAN SL EDITION, RGB, 360MM, BRANCO, GA-360SLA-WH', 'preco'=>'R$ 1.299,90', 'descricao'=>'	Water Cooler de Alto nível com boa performance sem sacrificar estilo e estéticas. Fans de alto desempenho tanto em fluxo de ar quanto em pressão estática. Um excelente cooler de CPU All-In-One agora possui UNI FAN SL 120. Fornece uma fan de alta pressão estática ARGB com velocidade variável de 800 a 1900 RPM e fluxo de ar nominal de 58,54 CFM.', 'imagem'=>'produto10.jpg'),
    10 => array('nome'=>'PLACA DE VIDEO PNY GEFORCE GTX 1650, 4GB, GDDR6, 128-BIT, VCG16504D6SFMPB1', 'preco'=>'R$ 1.559,00', 'descricao'=>'A GeForce® GTX 1650 foi desenvolvida com o desempenho gráfico inovador da premiada arquitetura NVIDIA TuringTM. Ela é a potência definitiva para os games atuais mais populares e oferece ainda mais velocidade para os títulos modernos. Jogue melhor com a GeForce GTX.', 'imagem'=>'produto11.jpg'),
    11 => array('nome'=>'TECLADO MECANICO GAMER REDRAGON FIZZ, RAINBOW, ABNT2 60%, SWITCH MARRON, PRETO, K617-R-B-(PT-BROWN)', 'preco'=>'R$ 169,90', 'descricao'=>'	Layout compacto 60% para os gamers que procuram deixar o máximo de espaço possível sobre a mesa. Cabo USB Tipo C removível para maior praticidade durante o transporte. Keycaps feitas com o método double shot injection resultando em legendas duradouras. Layout ABNT2 feito especialmente para o mercado brasileiro.', 'imagem'=>'produto12.jpg'),
)
?>